import functions_framework
import sys
import io
import traceback
import json

@functions_framework.http
def execute_python_script(request):
    """HTTP Cloud Function to execute Python code generated by PyBlox player."""

    try:
        request_json = request.get_json(silent=True)
        if not request_json or 'code' not in request_json:
            return json.dumps({"success": False, "error": " Field 'code' was not found in the request body."}), 400

        user_code = request_json['code']

        old_stdout = sys.stdout
        old_stderr = sys.stderr
        redirected_output = io.StringIO()
        redirected_error = io.StringIO()
        sys.stdout = redirected_output
        sys.stderr = redirected_error

        exec_globals = {}
        
        try:
            exec(user_code, exec_globals)
            
            output = redirected_output.getvalue()
            error = redirected_error.getvalue()
            
            response_data = {
                "success": True,
                "output": output,
                "error": error
            }
            return json.dumps(response_data), 200
        except Exception:
            error_message = traceback.format_exc()
            response_data = {
                "success": False,
                "output": redirected_output.getvalue(),
                "error": error_message
            }
            return json.dumps(response_data), 200
        finally:
            sys.stdout = old_stdout
            sys.stderr = old_stderr

    except Exception:
        error_message = traceback.format_exc()
        return json.dumps({"success": False, "error": f"Internal failure: {error_message}"}), 500